---
version: '3.3'

services:
  runner:
    image: github-runner:latest
    build:
      context: .
      args:
        RUNNER_VERSION: '2.304.0'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
